import axios from "axios";
import SHA256 from "crypto-js/sha256";

// Define a estrutura dos dados que vamos receber
interface ResearchMetadata {
    title: string;
    agent: string;
    topic: string;
    content: string;
}

export const uploadToPinata = async (metadata: ResearchMetadata) => {
    const url = `https://api.pinata.cloud/pinning/pinJSONToIPFS`;

    // 1. Calcular o Hash de Integridade (A Prova Matemática)
    // Se mudar uma vírgula no texto, esse hash muda totalmente.
    const integrityHash = SHA256(metadata.content).toString();

    // 2. Montar o JSON padrão NFT (OpenSea Standard)
    const data = JSON.stringify({
        pinataContent: {
            name: metadata.title,
            description: `Research generated by Zaeon Agent: ${metadata.agent}`,
            // Imagem padrão (depois você pode trocar por uma gerada por AI)
            image: "ipfs://QmY5M5t5oQ1hU5q8X5h5Z5h5Z5h5Z5h5Z5h5Z5h5Z5h5",
            attributes: [
                { trait_type: "Agent", value: metadata.agent },
                { trait_type: "Topic", value: metadata.topic },
                { trait_type: "Timestamp", value: new Date().toISOString() },
                { trait_type: "Integrity Proof", value: integrityHash }, // <--- O PULO DO GATO
                { trait_type: "Verification", value: "SHA-256" }
            ],
            // O conteúdo real do paper vai aqui
            content_text: metadata.content
        },
        pinataMetadata: {
            name: `ZAEON-${Date.now()}`
        }
    });

    try {
        const res = await axios.post(url, data, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.NEXT_PUBLIC_PINATA_JWT}`
            }
        });

        // Retorna o endereço final do IPFS
        return `ipfs://${res.data.IpfsHash}`;

    } catch (error) {
        console.error("ERRO NO PINATA:", error);
        alert("Erro ao subir para o IPFS. Verifique o console e sua chave API.");
        return null;
    }
};